#!/bin/ash

if [ "${DEBUG}" != "" ]; then
	printf "debuging \x1b[38:5:39mVsFTPd\x1b[00m \n\n"
	printf "FTP_USER          %s\n" "${FTP_USER}"
	printf "FTP_PASS          %s\n" "${FTP_PASS}"
	printf "FTP_PORT          %s\n" "${FTP_PORT}"
	printf "FTP_PASV_MIN_PORT %s\n" "${FTP_PASV_MIN_PORT}"
	printf "FTP_PASV_MAX_PORT %s\n" "${FTP_PASV_MAX_PORT}"
	printf "CERT_SUBJ         %s\n" "${CERT_SUBJ}"
	printf "DEBUG             %s\n\n" "${DEBUG}"
fi

function	ftp_create_ssl()
{
	mkdir -p /etc/vsftpd/ssl
	openssl req \
		-x509 \
		-newkey rsa:4096 \
		-sha256 \
		-nodes \
		-days 365 \
		-subj "${CERT_SUBJ}" \
		-keyout /etc/vsftpd/ssl/vsftpd-selfsigned.key \
		-out /etc/vsftpd/ssl/vsftpd-selfsigned.crt
}

function	ftp_configure()
{
	<< EOFCONF cat > /etc/vsftpd/vsftpd.conf
# Port Config
listen=YES
listen_address=0.0.0.0
listen_port=${FTP_PORT}
ftp_data_port=${FTP_DATA_PORT}

background=NO
local_enable=YES
write_enable=YES

# Configuring Chroot
chroot_local_user=YES
chroot_list_enable=NO
allow_writeable_chroot=YES

# Enable Passv
pasv_enable=YES
pasv_promiscuous=YES
pasv_address=0.0.0.0
pasv_min_port=${FTP_PASV_MIN_PORT}
pasv_max_port=${FTP_PASV_MAX_PORT}

# hardening
anonymous_enable=NO
seccomp_sandbox=NO
hide_ids=YES
anonymous_enable=NO

## allow list
userlist_deny=NO
userlist_enable=YES
userlist_file=/etc/vsftpd/allowed_users

## enable ssl
ssl_enable=YES
allow_anon_ssl=NO
force_local_data_ssl=YES
force_local_logins_ssl=YES
require_ssl_reuse=NO
ssl_ciphers=HIGH
rsa_cert_file=/etc/vsftpd/ssl/vsftpd-selfsigned.crt
rsa_private_key_file=/etc/vsftpd/ssl/vsftpd-selfsigned.key
EOFCONF
	echo "${FTP_USER}" > /etc/vsftpd/allowed_users
}

if [ ! -f /etc/vsftpd/allowed_users ]; then
	printf "VsFTPd \x1b[38:5:160mnot found\x1b[00m, initialize it\n"
	ftp_configure
	ftp_create_ssl
else
	printf "VsFTPd \x1b[38:5:76mfound\x1b[00m, Skiping initialization\n"
fi

chgrp -R "${FTP_USER}" "/home/${FTP_USER}"
chmod -R g=rwx "/home/${FTP_USER}"

printf "VsFTPd launched on port: \x1b[38:5:208m${FTP_PORT}\x1b[00m\n"

/usr/sbin/vsftpd /etc/vsftpd/vsftpd.conf
