version: "3.9"

services:

  nginx:
    container_name: nginx
    build:
      context: "./nginx"
      target: packed
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - 443:443
    networks:
      net_00:
        ipv4_address: "12.0.0.10"
    volumes:
      - nginx_root:/var/www/html

  wordpress:
    container_name: wordpress
    build:
      context: "./wordpress"
    environment:
      - ADMIN_PASS=${ADMIN_PASS}
      - NORMAL_USER=${NORMAL_USER}
      - NORMAL_PASS=${NORMAL_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 9000:9000
    networks:
      net_00:
        ipv4_address: "12.0.0.11"
    volumes:
      - wordpress_root:/var/www/html
    healthcheck:
      test: [ "CMD", "pgrep", "php81" ]
      interval: 2s
      timeout: 1s
      retries: 10

  mariadb:
    container_name: mariadb
    build:
      context: "./mariadb"
      target: "packed"
    environment:
      - ADMIN_PASS=${ADMIN_PASS}
      - NORMAL_USER=${NORMAL_USER}
      - NORMAL_PASS=${NORMAL_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - 3306:3306
    networks:
      net_00:
        ipv4_address: "12.0.0.12"
    volumes:
      - maria_db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "pgrep", "mysqld" ]
      interval: 2s
      timeout: 1s
      retries: 10

networks:
  net_00:
    name: net_00
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: net_00
    ipam:
      driver: default
      config:
        - subnet: 12.0.0.0/24
          ip_range: 12.0.0.0/24
          gateway: 12.0.0.1

volumes:

  maria_db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/mariadb

  nginx_root:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ~/data/nginx

  wordpress_root:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ~/data/wordpress
