version: "3.9"

services:

  nginx:
    container_name: nginx
    build:
      context: "./nginx"
      target: packed
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - 443:443
    networks:
      net_00:
        ipv4_address: "12.0.0.10"
    volumes:
      - www_root:/var/www/html
      - log_nginx:/var/log/nginx

  wordpress:
    container_name: wordpress
    build:
      context: "./wordpress"
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - NORMAL_USER=${NORMAL_USER}
      - NORMAL_PASS=${NORMAL_PASS}
      - DB_NAME=${DB_NAME}
      - WP_TITLE=${WP_TITLE}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 9000:9000
    networks:
      net_00:
        ipv4_address: "12.0.0.11"
    volumes:
      - www_root:/var/www/html
      - log_wordpress:/var/log/php81
    healthcheck:
      test: [ "CMD", "pgrep", "php81" ]
      interval: 2s
      timeout: 1s
      retries: 10

  mariadb:
    container_name: mariadb
    build:
      context: "./mariadb"
      target: "packed"
    environment:
      - ADMIN_PASS=${ADMIN_PASS}
      - NORMAL_USER=${NORMAL_USER}
      - NORMAL_PASS=${NORMAL_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - 3306:3306
    networks:
      net_00:
        ipv4_address: "12.0.0.12"
    volumes:
      - maria_db:/var/lib/mysql
      - log_mariadb:/var/log/mariadb
    healthcheck:
      test: [ "CMD", "pgrep", "mysqld" ]
      interval: 2s
      timeout: 1s
      retries: 10

networks:
  net_00:
    name: net_00
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: net_00
    ipam:
      driver: default
      config:
        - subnet: 13.37.42.0/24
          ip_range: 13.37.42.0/24
          gateway: 13.37.42.1

volumes:

  maria_db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/mariadb

  www_root:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/www_root

  log_mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/log/mariadb

  log_nginx:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/log/nginx

  log_wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/log/wordpress
