version: "3.9"

################################################################################
# DEFAULT CONF https://stackoverflow.com/a/65522511

x-healthcheck_conf: &healthcheck_conf
      interval: 1s
      timeout: 1s
      retries: 50

################################################################################

services:

  ##############################################################################
  # MARIADB
  mariadb:
    container_name: mariadb
    build:
      context: "./mariadb"
      target: "packed"
    environment:
      - DB_ADMIN_USER=${ADMIN_USER}
      - DB_ADMIN_PASS=${ADMIN_PASS}
      - DB_NAME=${DB_NAME}
      - DEBUG=${DEBUG:-0}
    networks:
      main_net:
        ipv4_address: "13.37.42.12"
    volumes:
      - maria_db:/var/lib/mysql
      - log_mariadb:/var/log/mariadb
    healthcheck:
      test: [ "CMD", "pgrep", "mysqld" ]
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # WORDPRESS
  wordpress:
    container_name: wordpress
    build:
      context: "./wordpress"
    environment:
      - WP_TITLE=${WP_TITLE}
      - WP_ROOT=${WP_ROOT}
      - WP_ADMIN_USER=${ADMIN_USER}
      - WP_ADMIN_PASS=${ADMIN_PASS}
      - WP_NORMAL_USER=${NORMAL_USER}
      - WP_NORMAL_PASS=${NORMAL_PASS}
      - DB_NAME=${DB_NAME}
      - CERT_SUBJ=${CERT_SUBJ}
      - REDIS_PASS=${ADMIN_PASS}
      - DEBUG=${DEBUG:-0}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      main_net:
        ipv4_address: "13.37.42.11"
    volumes:
      - www_root:/var/www/html
      - log_wordpress:/var/log/php81
    healthcheck:
      test: [ "CMD", "pgrep", "php81" ]
      << : *healthcheck_conf
      start_period: 5s
  #
  ##############################################################################

  ##############################################################################
  # NGINX
  nginx:
    container_name: nginx
    build:
      context: "./nginx"
      target: packed
    environment:
      - CERT_SUBJ=${CERT_SUBJ}
      - DEBUG=${DEBUG:-0}
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - 443:443
    networks:
      main_net:
        ipv4_address: "13.37.42.10"
    volumes:
      - nginx_conf:/etc/nginx
      - www_root:/var/www/html
      - log_nginx:/var/log/nginx
    healthcheck:
      test: [ "CMD", "pgrep", "nginx" ]
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # Redis
  redis:
    container_name: redis
    build:
      context: "./redis"
      target: packed
    environment:
      - REDIS_PASS=${ADMIN_PASS}
      - DEBUG=${DEBUG:-0}
    networks:
      main_net:
        ipv4_address: "13.37.42.15"
    healthcheck:
      test: [ "CMD", "pgrep", "redis" ]
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # Static Site
  static_site:
    container_name: static_site
    build:
      context: "./static_site"
      target: "packed"
    environment:
      - DEBUG=${DEBUG:-0}
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      main_net:
        ipv4_address: "13.37.42.16"
    volumes:
      - www_root:/var/www/html
  #
  ##############################################################################

  ##############################################################################
  # VSFTPD
  vsftpd:
    container_name: vsftpd
    build:
      context: "./vsftpd"
      target: "packed"
      args:
        FTP_USER: ${ADMIN_USER}
        FTP_PASS: ${ADMIN_PASS}
    environment:
      - FTP_USER=${ADMIN_USER}
      - FTP_PASS=${ADMIN_PASS}
      - FTP_PORT=${FTP_PORT:-21}
      - FTP_DATA_PORT=${FTP_DATA_PORT:-20}
      - FTP_PASV_MIN_PORT=${FTP_PASV_MIN_PORT:-10000}
      - FTP_PASV_MAX_PORT=${FTP_PASV_MAX_PORT:-10100}
      - CERT_SUBJ=${CERT_SUBJ}
      - DEBUG=${DEBUG:-0}
    depends_on:
      nginx:
        condition: service_healthy
    ports:
      - ${FTP_PORT:-21}:${FTP_PORT:-21}
      - ${FTP_DATA_PORT:-20}:${FTP_DATA_PORT:-20}
      - ${FTP_PASV_MIN_PORT:-10000}-${FTP_PASV_MAX_PORT:-10100}:${FTP_PASV_MIN_PORT:-10000}-${FTP_PASV_MAX_PORT:-10100}
    networks:
      main_net:
        ipv4_address: "13.37.42.13"
    volumes:
      - www_root:/home/${ADMIN_USER}
      - vsftpd_conf:/etc/vsftpd
    healthcheck:
      test: [ "CMD", "pgrep", "vsftpd" ]
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # Adminer
  adminer:
    container_name: adminer
    build:
      context: "./adminer"
      target: "packed"
    environment:
      - ADMIN_PASS=${ADMIN_PASS}
      - DEBUG=${DEBUG:-0}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 80:80
    volumes:
      - www_root:/var/www/html
    networks:
      main_net:
        ipv4_address: "13.37.42.17"
    healthcheck:
      test: [ "CMD", "pgrep", "php" ]
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # Custom
  portainer:
    container_name: portainer
    build:
      context: "./portainer"
      target: "packed"
    environment:
      - CERT_SUBJ=${CERT_SUBJ}
      - ADMIN_PASS=${ADMIN_PASS}
      - DEBUG=${DEBUG:-0}
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      main_net:
        ipv4_address: "13.37.42.18"
    healthcheck:
      test: [ "CMD", "pgrep", "portainer" ]
      << : *healthcheck_conf
  #
  ##############################################################################

networks:
  ##############################################################################
  # MAIN INTERNAL NETWORK
  main_net:
    name: main_net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: main_net
    ipam:
      driver: default
      config:
        - subnet: 13.37.42.0/27
          ip_range: 13.37.42.0/27
          gateway: 13.37.42.1
  #
  ##############################################################################

volumes:
  ##############################################################################
  # MariaDB Database
  maria_db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/mariadb
  #
  ##############################################################################

  ##############################################################################
  # VSFTPD CONFIG
  vsftpd_conf:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/vsftpd
  #
  ##############################################################################

  ##############################################################################
  # VSFTPD CONFIG
  nginx_conf:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/nginx
  #
  ##############################################################################

  ##############################################################################
  # HTML PART
  www_root:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/www_root
  #
  ##############################################################################

  ##############################################################################
  # Portainer build
  portainer_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/portainer
  #
  ##############################################################################

  ##############################################################################
  # SOME LOGS
  log_mariadb:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/log/mariadb

  log_nginx:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/log/nginx

  log_wordpress:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/log/wordpress
  #
  ##############################################################################
