#!/bin/ash

if [ "${DEBUG}" != "0" ]; then
	printf "debuging \x1b[38:5:39mMariaDB\x1b[00m \n\n"
	printf "DB_ADMIN_USER %s\n" "${DB_ADMIN_USER}"
	printf "DB_ADMIN_PASS %s\n" "${DB_ADMIN_PASS}"
	printf "DB_NAME       %s\n" "${DB_NAME}"
	printf "DEBUG         %s\n\n" "${DEBUG}"
fi

MYSQL_OPT="--user=mysql --verbose=0 --skip-name-resolve --skip-networking=0"

if [ ! -d /run/mysqld ]; then
	mkdir -p /run/mysqld
fi

chown -R mysql:mysql /run/mysqld

if [ ! -d /var/lib/mysql/mysql ]; then

	printf "MariaDB \x1b[38:5:160mnot found\x1b[00m, initialize it\n"

	chown -R mysql:mysql /var/lib/mysql
	chown -R mysql:mysql /var/log/mariadb

	mysql_install_db --user="mysql" --ldata=/var/lib/mysql >/dev/null

	tmp_file=$(mktemp)

	cat << EOFSQL > "${tmp_file}"
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE ${DB_NAME};
FLUSH PRIVILEGES ;
GRANT ALL ON ${DB_NAME}.* TO '${DB_ADMIN_USER}'@'%' identified by '${DB_ADMIN_PASS}' WITH GRANT OPTION ;
SET PASSWORD FOR '${DB_ADMIN_USER}'@'%'=PASSWORD('${DB_ADMIN_PASS}') ;
DROP DATABASE IF EXISTS test ;
FLUSH PRIVILEGES ;
EOFSQL

	mysqld --bootstrap ${MYSQL_OPT} < "${tmp_file}"
	rm "${tmp_file}"
else
	printf "MariaDB \x1b[38:5:76mfound\x1b[00m, Skiping initialization\n"
fi
printf "MariaDB launched on port: \x1b[38:5:208m3306\x1b[00m\n"

/usr/bin/mysqld --console ${MYSQL_OPT}
