#!/bin/ash

MYSQL_OPT="--user=mysql --verbose=0"

if [ ! -d "/run/mysqld" ]; then
	mkdir -p /run/mysqld
	chown -R mysql:mysql /run/mysqld
fi

if [ ! -d /var/lib/mysql/mysql ]; then
	chown -R mysql:mysql /var/lib/mysql

	mysql_install_db --user="mysql" --basedir=/usr --datadir=/var/lib/mysql --rpm >/dev/null

	/usr/bin/mysqld ${MYSQL_OPT} --console $!
	tmp_mysqld="${!}"

	mysql -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8 COLLATE utf8_general_ci;"
	mysql -e "USE ${DB_NAME};"
	mysql -e "CREATE USER 'root'@'%' IDENTIFIED BY '${ADMIN_PASS}';"
	mysql -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO 'root'@'%';"
	mysql -e "DROP DATABASE IF EXISTS test ;"
	mysql -e "FLUSH PRIVILEGES ;"

	kill ${tmp_mysqld}
	wait ${tmp_mysqld}
fi

exec /usr/bin/mysqld ${MYSQL_OPT} --console
