#!/bin/ash

if [ "${DEBUG}" != "0" ]; then
	printf "debuging \x1b[38:5:39mRedis\x1b[00m \n\n"
	printf "DEBUG         %s\n\n" "${DEBUG}"
fi

if [ ! -d /etc/redis.conf.bak ]; then
	printf "Redis \x1b[38:5:160mnot found\x1b[00m, initialize it\n"

	cp /etc/redis.conf /etc/redis.conf.bak

	sed -i "s|bind 127.0.0.1|#bind 127.0.0.1|g" /etc/redis.conf
	sed -i "s|# requirepass foobared|requirepass ${REDIS_PASS}|g" /etc/redis.conf
	sed -i "s|# maxmemory <bytes>|maxmemory 2mb|g" /etc/redis.conf
	sed -i "s|# maxmemory-policy noeviction|maxmemory-policy allkeys-lru|g" /etc/redis.conf
else
	printf "Redis \x1b[38:5:76mfound\x1b[00m, Skiping initialization\n"
fi

printf "Redis launched on port: \x1b[38:5:208m6379\x1b[00m\n"

redis-server --protected-mode no
