#!/bin/ash

if [ "${DEBUG}" != "0" ]; then
	printf "debuging \x1b[38:5:39mRedis\x1b[00m \n\n"
	printf "REDIS_PASS %s" "${REDIS_PASS}"
	printf "DEBUG      %s\n\n" "${DEBUG}"
fi

function	redis_configure()
{
	cp /etc/redis.conf /etc/redis.conf.bak
	sed -i "s|bind 127.0.0.1|#bind 127.0.0.1|g" /etc/redis.conf
	sed -i "s|# requirepass foobared|requirepass ${REDIS_PASS}|g" /etc/redis.conf
	sed -i "s|# maxmemory <bytes>|maxmemory 2mb|g" /etc/redis.conf
	sed -i "s|# maxmemory-policy noeviction|maxmemory-policy allkeys-lru|g" /etc/redis.conf
}

if [ ! -f /etc/redis.conf.bak ]; then
	printf "Redis \x1b[38:5:160mnot found\x1b[00m, initialize it\n"

	redis_configure
else
	printf "Redis \x1b[38:5:76mfound\x1b[00m, Skiping initialization\n"
fi

printf "Redis launched on port: \x1b[38:5:208m6379\x1b[00m\n"

redis-server --protected-mode no
