#!/bin/ash

mkdir /var/www/html/wordpress

cd /var/www/html/wordpress

wp core download --allow-root

wp config create \
	--dbname=${DB_NAME} \
	--dbuser=root \
	--dbpass=${ADMIN_PASS} \
	--dbhost=mariadb \
	--allow-root \
	--extra-php

wp core install \
	--url=https://brda-sil.42.fr \
	--title="Mine Site" \
	--admin_user=${ADMIN_USER} \
	--admin_password=${ADMIN_PASS} \
	--admin_email="pix@nowhere.com" \
	--allow-root

wp user create ${NORMAL_USER} \
	brda-sil@nowhere.com \
	--user_pass=${NORMAL_PASS} \
	--role=subscriber \
	--allow-root

# wp theme install twentyseventeen --allow-root
# wp theme activate twentyseventeen --allow-root

printf "Launching wordpress on port :9000\n"

/usr/sbin/php-fpm81 -F -R
