#!/bin/ash

if [ "${DEBUG}" != "" ]; then
	printf "debuging \x1b[38:5:39mWordPress\x1b[00m \n\n"
	printf "WP_TITLE       %s\n" "${WP_TITLE}"
	printf "WP_ROOT        %s\n" "${WP_ROOT}"
	printf "WP_ADMIN_USER  %s\n" "${WP_ADMIN_USER}"
	printf "WP_ADMIN_PASS  %s\n" "${WP_ADMIN_PASS}"
	printf "WP_NORMAL_USER %s\n" "${WP_NORMAL_USER}"
	printf "WP_NORMAL_PASS %s\n" "${WP_NORMAL_PASS}"
	printf "DB_NAME        %s\n" "${DB_NAME}"
	printf "REDIS_PASS     %s\n" "${REDIS_PWD}"
	printf "DEBUG          %s\n\n" "${DEBUG}"
fi

function	wp_download()
{
	cd /var/www/html/

	wget https://wordpress.org/latest.tar.gz -O latest.tar.gz
	tar xf latest.tar.gz && rm -rf latest.tar.gz

	if [ "${WP_ROOT}" != "wordpress" ]; then
		mv wordpress "${WP_ROOT}"
	fi
	cd "${WP_ROOT}"
}

function	wp_configure()
{
	wp config create \
		--dbname="${DB_NAME}" \
		--dbuser="${WP_ADMIN_USER}" \
		--dbpass="${WP_ADMIN_PASS}" \
		--dbhost=mariadb \

	wp core install \
		"--url=https://brda-sil.42.fr/${WP_ROOT}" \
		--title="${WP_TITLE}" \
		--admin_user="${WP_ADMIN_USER}" \
		--admin_password="${WP_ADMIN_PASS}" \
		--admin_email="${WP_ADMIN_USER}@nowhere.com" \
		--skip-email

	wp user create "${WP_NORMAL_USER}" "${WP_NORMAL_USER}@nowhere.com" \
		--user_pass="${WP_NORMAL_PASS}" \
		--role=contributor

	wp theme activate twentytwentytwo
}

function	wp_configure_redis()
{
	# enable redis cache
	sed -i "40i define( 'WP_REDIS_HOST', 'redis' );" wp-config.php
	sed -i "41i define( 'WP_REDIS_PORT', 6379 );" wp-config.php
	sed -i "42i define( 'WP_REDIS_PASSWORD', '${REDIS_PWD}' );" wp-config.php
	sed -i "42i define( 'WP_REDIS_TIMEOUT', 1 );" wp-config.php
	sed -i "43i define( 'WP_REDIS_READ_TIMEOUT', 1 );" wp-config.php
	sed -i "44i define( 'WP_REDIS_DATABASE', 0 );\n" wp-config.php

	redis-cli -h redis flushall

	wp plugin install redis-cache --activate
}

function	wp_hardening()
{
	wp plugin delete $(wp plugin list --status=inactive --field=name)
	wp theme delete $(wp theme list --status=inactive --field=name)
	wp plugin update --all
}

if [ ! -d /var/www/html/wordpress ]; then
	printf "WordPress \x1b[38:5:160mnot found\x1b[00m, initialize it\n"

	wp_download
	wp_configure
	wp_configure_redis
	wp_hardening
else
	printf "WordPress \x1b[38:5:76mfound\x1b[00m, Skiping initialization\n"
fi

printf "WordPress launched on port: \x1b[38:5:208m9000\x1b[00m\n"

/usr/sbin/php-fpm81 -F -R
