#!/bin/ash

if [ "${DEBUG}" != "" ]; then
	printf "debuging \x1b[38:5:39mAdminer\x1b[00m \n\n"
	printf "DEBUG         %s\n\n" "${DEBUG}"
fi

BASE_DIR="/var/www/html/adminer"

function	adminer_configure()
{
	mkdir -p "${BASE_DIR}"
	curl -L "http://www.adminer.org/latest.php" --output "${BASE_DIR}/adminer.php"
}

function	adminer_enable_plugin()
{
	mkdir -p "${BASE_DIR}/plugins"
	curl -L "https://raw.githubusercontent.com/vrana/adminer/master/plugins/plugin.php" \
		--output "${BASE_DIR}/plugins/plugin.php"
	curl -L "https://raw.githubusercontent.com/vrana/adminer/master/plugins/sql-log.php" \
		--output "${BASE_DIR}/plugins/sql-log.php"
}

if [ ! -f "${BASE_DIR}/adminer.php" ]; then
	printf "Adminer \x1b[38:5:160mnot found\x1b[00m, initialize it\n"

	adminer_configure
	adminer_enable_plugin
else
	printf "Adminer \x1b[38:5:76mfound\x1b[00m, Skiping initialization\n"
fi

printf "Adminer launched on port: \x1b[38:5:208m80\x1b[00m\n"

cd ${BASE_DIR}

/usr/bin/php \
	-S 0.0.0.0:80 \
	-t ${BASE_DIR}
