#!/bin/ash

if [ "${DEBUG}" != "" ]; then
	printf "debuging \x1b[38:5:39mAdminer\x1b[00m \n\n"
	printf "DEBUG         %s\n\n" "${DEBUG}"
fi

if [ ! -f /var/www/html/adminer.php ]; then
	printf "Adminer \x1b[38:5:160mnot found\x1b[00m, initialize it\n"
	curl -L "http://www.adminer.org/latest.php" --output /var/www/html/adminer.php
else
	printf "Adminer \x1b[38:5:76mfound\x1b[00m, Skiping initialization\n"
fi

printf "Adminer launched on port: \x1b[38:5:208m80\x1b[00m\n"

/usr/bin/php -S 0.0.0.0:80 /var/www/html/adminer.php
